### Recipe Requests

### Request: Create a recipe
POST http://localhost:3000/recipes HTTP/1.1
content-type: application/json

{
    "name": "Test Recipe",
    "servings": 7,
    "cals_per_serving": 456
}

### Request: Retrieve all the recipes
GET http://localhost:3000/recipes HTTP/1.1

### Request: Retrieve recipe with specified id
GET http://localhost:3000/recipes/4 HTTP/1.1


### Update a recipe
PUT http://localhost:3000/recipes/2 HTTP/1.1
content-type: application/json

{
    "name": "Quiche",
    "servings": 4,
    "cals_per_serving": 456
}

### Request: Delete a recipe
DELETE http://localhost:3000/recipes/5 HTTP/1.1


### Ingredient Requests

### Request: Create an ingredient
POST http://localhost:3000/ingredients HTTP/1.1
content-type: application/json

{
    "name": "Test Ingredient",
    "serving_size": 18.4,
    "calories": 99,
    "cals_per_100g": 14.3
}

### Request: Retrieve all the ingredients
GET http://localhost:3000/ingredients HTTP/1.1

### Request: Retrieve ingredient with specified id
GET http://localhost:3000/ingredients/10 HTTP/1.1


### Update an ingredient
PUT http://localhost:3000/ingredients/10 HTTP/1.1
content-type: application/json

 {
    "name": "Test Ingredient",
    "serving_size": 18.4,
    "calories": 90,
    "cals_per_100g": 14.3
  }

### Request: Delete an ingredient
DELETE http://localhost:3000/ingredients/10 HTTP/1.1


### Recipe Ingredient Requests

### Request: Add an ingredient to a recipe
POST http://localhost:3000/recipes/4/ingredients HTTP/1.1
content-type: application/json

{
    "ingredient_id": 8,
    "quantity": "2 C",
    "grams": 130
}

### Request: Retrieve all the ingredients for a recipe
GET http://localhost:3000/recipes/2/ingredients HTTP/1.1


### Update a recipe ingredient
PUT http://localhost:3000/recipes/4/ingredients/8 HTTP/1.1
content-type: application/json

{
    "quantity": "3 C",
    "grams": 120
}

### Request: Remove an ingredient from a recipe
DELETE http://localhost:3000/recipes/4/ingredients/8 HTTP/1.1
